name: Compile and upload résumé PDF
on:
    push:
        branches:
            - "main"
        paths:
            - "**.tex"
            - "**.html"
            - "CNAME"
            - ".github/workflows/**"
    pull_request:
        branches:
            - "main"
        paths:
            - "**.tex"
            - "**.html"
            - "CNAME"
            - ".github/workflows/**"

permissions:
    contents: write

jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Github Action for LaTeX
              uses: xu-cheng/latex-action@v2    
              with:
                  root_file: |
                    resume.tex

            - name: Post Processing
              run: |
                  mkdir build
                  cp CNAME build/
                  cp *.html build/
                  cp resume.pdf build/ 
                  mv build/resume.pdf build/vineet-anil-likhitkar-resume.pdf
                  
            - name: Git add
              run: git add resume.pdf
              
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4.4.3            
              with:
                  branch: gh-pages
                  folder: build
                  clean: true
              
